### ISSUE TITLE
Outdated builds for Samsung S9 (starlte) --- support for lineageOS 17.1?

### ISSUE THREAD

**Issue by NEET-FEET** [lineageos4microg/lineageos4microg.github.io#48] opened 2020-07-21 15:45 UTC
I've been running LineageOS for MicroG for a while now, LineageOS stopped officially supporting Starlte for a period but it has resumed support by a new maintainer. LineageOS for MicroG still has the old builds, is this due that the new builds are LineageOS 17.1 or some other reason? 
If it is due to version bump, are you guys working on supporting 17.1 or is that still far away?

**Comment by EchedeyLR** [comment] 2020-09-15 21:37
The issue is not only dedicated to Samsung S9, every smartphone in which LineageOS abandoned its support and deleted their builds had old builds in LineageOS from microG as an archive (with the difference of microG apps and signature spoofing support). 

Since the same date new builds for 17.1 were uploaded for supported smartphones, old builds were deleted at all including smartphones not supported from a lot of time ago.

I am also worried about it.

**Comment by famo** [comment] 2021-02-06 12:40
Please check if this issue is still valid. I'm seeing new builds.

**Comment by petefoth** [comment] 2024-01-15 20:55
Closing as up-to-date builds are available [here](https://download.lineage.microg.org/starlte/), and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks

**Closed by petefoth** 2024-01-15 20:55 UTC
